export { HeroSection } from "./HeroSection";
export { LeadMagnetSection } from "./LeadMagnetSection";
export { ValuePropsSection } from "./ValuePropsSection";
export { CareerPathsSection } from "./CareerPathsSection";
export { CertificationSection } from "./CertificationSection";
export { ResourcesSection } from "./ResourcesSection";
export { SocialProofSection } from "./SocialProofSection";
export { CoursePreviewSection } from "./CoursePreviewSection";
export { QuickSurveySection } from "./QuickSurveySection";
export { default as PricingSection } from "./PricingSection";
export { WaitlistSection } from "./WaitlistSection";
export { Footer } from "./Footer";
